### ISSUE TITLE
Show the number of instances that use a given container profile

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/space-barnacle#8]

**Comment by helrond** [comment]
The point of this requirement was to tell users which container profiles are preferred. However, looping through all of the instances to get a count of container profiles is going to take a long time. How about if we have a static list of preferred container sizes?

**Comment by eswanson611** [comment]
I think a static list is better for MVP. Running through all instances sounds time-consuming and can be done later if necessary.

**Comment by jwelbs** [comment]
How easy could that static list be to update?

**Comment by helrond** [comment]
@jwelbs good question. I think it would require editing a static file with IDs or URIs of container profiles, kind of like updating an `app-config.js` file as specified here: https://github.com/RockefellerArchiveCenter/space-barnacle/blob/611397d7d6dd9ec3f017ad8d4f70090a0796b514/README.md#installation

**Comment by EcZX** [comment]
Limit to how large this static file can be?

**Comment by EcZX** [comment]
Is it possible to make "space barnacle thinking inside the box"'s font a little bigger? Also is it possible to make it change colors when you hover over it?

**Comment by jwelbs** [comment]
When testing sizes I found that the options that remain for larger items are few so it is easy for the user to quickly determine what their limited options are and make an informed decision. However, when testing Space Barnacle for small items, the wealth of boxes that an item fits is too great. Even using the sort function, it is hard to determine the which box is a good fit. Has anyone else had this problem?

**Comment by helrond** [comment]
@EcZX can you open a new issue for:

> Is it possible to make "space barnacle thinking inside the box"'s font a little bigger? Also is it possible to make it change colors when you hover over it?

Thanks!
