### ISSUE TITLE
Printer-friendly page

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/space-barnacle#9]

**Comment by helrond** [comment]
@jwelbs do you consider this an MVP requirement?

**Comment by helrond** [comment]
The answer is yes!

**Comment by jwelbs** [comment]
Tested out printing a list generated with test data and it looks good/clear to me.

**Comment by helrond** [comment]
@jwelbs do you think we need a print button?

**Comment by jwelbs** [comment]
Yes and I think it should say "Print List"

**Comment by helrond** [comment]
I have added a separate issue for this, #22 
Closing this issue.
